WordPress/two-factor

- .travis.yml
Core is testing them (https://core.trac.wordpress.org/browser/trunk/.travis.yml)
> Add PHP 5.6, 7.0 and HHVM to test

- providers/class.two-factor-backup-codes.php
- providers/class.two-factor-dummy.php
- providers/class.two-factor-email.php
- providers/class.two-factor-provider.php
- providers/class.two-factor-totp.php
This PR solves 2 issues:
* Blank line found after control structure
* Multi-line function call not indented correctly
> Fix CodeSniffer Errors

- providers/class.two-factor-email.php
- tests/phpunit/tests/class.two-factor-core.php
- tests/phpunit/tests/providers/class.two-factor-dummy.php
- tests/phpunit/tests/providers/class.two-factor-email.php
I started by adding test coverage for the email provider and a few basic tests for the core class. In addition, I added a few safety checks in email. Also using the mockmailer so email output can be tested (used in one test at the moment). Please let me know what you think.
Thanks!
> Add email provider tests, some core tests, and small bug fixes

- class.two-factor-core.php
This way is more convenient for users.
> Use same provider after failed login

- .jshintrc
Copied from https://core.trac.wordpress.org/browser/trunk/.jshintrc
> Add .jshintrc

- providers/class.two-factor-fido-u2f-admin.php
- providers/class.two-factor-fido-u2f.php
- providers/js/fido-u2f-admin.js
- providers/js/fido-u2f-login.js
`wp_enqueue_script()` is better than `<script>` tag for security and maintainability.
And move scripts to the footer for performance.
> FIDO U2F: Improvements on JS loading

- class.two-factor-core.php
Related #37
This is kinder for admin and developers.
> FIDO U2F: Add error message for PHP version

- providers/class.two-factor-totp.php
- tests/phpunit/tests/providers/class.two-factor-totp.php
Here's a proposal for an initial set of tests for the TOTP code (https://github.com/georgestephanis/two-factor/issues/51).
> First pass of TOTP tests

- class.two-factor-core.php
- tests/phpunit/tests/class.two-factor-core.php
Some tests against the two-factor-core class with a few sanity checks for unset/malformed variables.
> Tests against main class with fixes

- class.two-factor-core.php
> Handle interim logins

- providers/class.two-factor-fido-u2f-admin-list-table.php
- providers/class.two-factor-fido-u2f-admin.php
- providers/js/fido-u2f-admin-inline-edit.js
*Based on inline edit code of post.*
> FIDO U2F: Add rename feature

- providers/class.two-factor-fido-u2f-admin-list-table.php
`<form>` in `<form>` is not valid!
Fixes #67
> FIDO U2F: Fix invalid HTML

- providers/class.two-factor-totp.php
> TOTP: Fix issue with pack on PHP 5.6.3+ in 32bit mode.

- .jscsrc
- .travis.yml
- providers/class.two-factor-fido-u2f.php
- providers/js/fido-u2f-admin-inline-edit.js
- providers/js/fido-u2f-admin.js
- providers/js/fido-u2f-login.js
I'll fix the ones on the master branch real quick.
> Travis is not properly checking JSCS

- application-passwords.js
- class.application-passwords.php
This pull is still a work in progress.
We should leverage the core REST API for managing application passwords instead of custom admin-ajax endpoints.
> Use the Core REST API for Application Passwords

- providers/class.two-factor-fido-u2f.php
> remove use of HTTP_HOST to 1) avoid warnings and 2) be more secure

- .coveralls.yml
- composer.json
> Use satooshi/php-coveralls 1.0.x, not 2.x

- readme.md
- readme.txt
> Updated README to reflect the plugin was tested with Wordpress 4.6.1

- class.two-factor-core.php
random_compat has shipped with WordPress since 4.4.0
> Use random_bytes()

- providers/class.two-factor-totp.php
> Don't show QR error when totp method is not enabled

- class.two-factor-core.php
> Only show fully configured providers as enabled

- providers/class.two-factor-fido-u2f.php
- providers/js/fido-u2f-login.js
> Load FIDO U2F JS only when needed

- readme.txt
> add temporary changelog with link to GH commits page.

- providers/class.two-factor-totp.php
> TOTP: Remove 'View Options' when totp is configured.

- includes/Yubico/U2F.php
- Implements https://github.com/Yubico/php-u2flib-server/pull/55
- Maybe fixes #193
> Sync upstream php-u2flib

- providers/class.two-factor-totp.php
> Encode name in OTP QR

- class.two-factor-core.php
> Add CSS overrides for the Jetpack SSO

- .travis.yml
- class.two-factor-core.php
- providers/class.two-factor-email.php
- providers/class.two-factor-provider.php
- tests/providers/class.two-factor-email.php
Fixes #177 which was introduced in #160, #155.
> Email: Resend Token

- class.two-factor-core.php
- providers/class.two-factor-backup-codes.php
- providers/class.two-factor-email.php
- providers/class.two-factor-fido-u2f-admin-list-table.php
- providers/class.two-factor-fido-u2f-admin.php
- providers/class.two-factor-fido-u2f.php
- providers/class.two-factor-totp.php
- tests/class.two-factor-core.php
- tests/providers/class.two-factor-backup-codes.php
- tests/providers/class.two-factor-dummy.php
- tests/providers/class.two-factor-email.php
- tests/providers/class.two-factor-fido-u2f.php
- tests/providers/class.two-factor-totp.php
- tests/two-factor.php
There is quite a bit of missing docblock information that makes it difficult to efficiently run tests and for IDEs to parse what each function/method should be doing and when. 
This is a small, incremental improvement in documentation that gets the documentation slightly closer to being useful and effective.
> Incremental Docblock Updates

- .gitignore
- .travis.yml
- composer.json
- package.json
- phpcs.xml
- phpunit.xml
- providers/class.two-factor-fido-u2f.php
- Enforce a specific version of WPCS.
- Install wp-dev-lib via Composer instead of npm.
> Introduce local WPCS

- includes/function.login-header.php
Fixes #245.
Ready for code review.
> Introduce the missing wp_login_viewport_meta

- two-factor.php
- Bump plugin version to 0.4.8.
> Release 0.4.8

- composer.json
> Sync license references, add project URLs to Composer

- includes/Google/u2f-api.js
- providers/class.two-factor-backup-codes.php
- providers/class.two-factor-fido-u2f-admin-list-table.php
> fix some typing mistakes

- .travis.yml
- readme.md
- readme.txt
- tests/class.two-factor-core.php
- two-factor.php
> WP core no longer supports older versions of PHP

- composer.json
Remaining reference in `composer.json`.
> Match the overall PHP compatibility

- class-two-factor-core.php
- Don't keep the first session token around.
> Invalidate the first session token

- readme.md
- readme.txt
stephanis.info is returning 404
> Update blog post URL

- providers/class.two-factor-totp.php
> remove spaces from TOTP codes

- .gitignore
- composer.json
- composer.lock
Set the PHP version in `composer.json` to ensure we pull in the correct dependencies for the minimum supported version of PHP.
> Fix the GitHub repo URL and track Composer deps

- class-two-factor-core.php
- providers/class.two-factor-fido-u2f-admin-list-table.php
- providers/class.two-factor-fido-u2f-admin.php
- providers/class.two-factor-fido-u2f.php
- providers/js/fido-u2f-admin-inline-edit.js
> Allow admins to configure U2F keys for other users

- providers/class.two-factor-totp.php
- readme.md
- readme.txt
- two-factor.php
Mark version 0.5.2 with all the bug fixes.
> Version 0.5.2

- providers/class-two-factor-totp.php
> restore space removal in authcode

- class-two-factor-core.php
Use the login_site_html_link hook just like in wp-login.php
> login_site_html_link hook fix

- composer.lock
- package-lock.json
- package.json
- readme.md
- readme.txt
- Mark as tested with WP 5.8.
- Update Node and Composer development packages.
> Update WP version tested and the dev tooling

- class-two-factor-core.php
- includes/function.login-footer.php
- includes/function.login-header.php
wp_no_robots is deprecated since WP 5.7.
Change login_header function to mimic login_header function from wp-login.php
> Update function.login-header.php to be compatible with WP 5.7

- .distignore
- two-factor.php
> Release 0.7.1

- providers/class-two-factor-email.php
Implemented the safe string hash function comparison between two hashes based on issue #425
> Implemented Hash Equal Function instead of !== based on issue #425

- readme.txt
- two-factor.php
Bumped version to `0.8.1`
The only change in this release is the fatal error bug fix from #547
See #549 for release process
> Release `0.8.1`

- readme.txt
- two-factor.php
This merges [the version bump from from the 0.8.2 branch](https://github.com/WordPress/two-factor/pull/570/commits/30e3d1f137fbad1708ab20257ea8f789b31c7656) to the main branch.
See #570
> Bump version identifier

- readme.txt
This PR has been tested against new WP 6.6 and updated the version for tested upto under `readme.txt` to 6.6
This is necessary as WP 6.6 is nearing to the release.
> Bump tested upto version to WP 6.6

- Gruntfile.js
- package-lock.json
- package.json
Removes some old `grunt deploy` code that was replaced in #543 
Since this code is no longer used, it's existence can be confusing. Removing it simplifies other PRs.
N/A - Not changelog worthy.
> Remove old grunt deploy related code. See #543

- readme.txt
- two-factor.php
Improve plugin discoverability on WP.org when searching for generic two-factor terms like `2fa`.
Fixes #631.
- Update short description to include `2FA`.
- Update plugin credits to `WordPress.org community` to be more specific and "official".
Documentation: include 2FA keyword in plugin description and update contributor reference to "WordPress.org community".
> Improve discoverability

- readme.txt
- two-factor.php
> Release 0.14.1
