class.two-factor-core.php
This filter, added to `Two_Factor_Core::get_provider_for_user()` serves two purposes:
1. Enables developers to set a default two-factor provider (e.g. "if the user hasn't explicitly made a decision default to `$provider`")
2. Enables developers to **force** a specific method when necessary.
=> Add the 'two_factor_provider_for_user' filter

class.two-factor-core.php, providers/class.two-factor-fido-u2f.php
All characters of "FIDO U2F" is capitalized in FIDO website.
=> Correct Proper Noun Notation

providers/class.two-factor-email.php
The `<kbd>` tags here are being displayed because they're being passed through esc_html(). I don't really think they're needed.
=> Remove <kbd> tags that are being escaped and displayed

tests/phpunit/includes/bootstrap.php
Hi! I was trying to get the unit testing up and running, but hit a couple of snags. The main was was the use of is_plugin_active, which under my testing environment here wasn't registering two-factor/two-factor.php. I changed bootstrap to require the code and to set the active_plugins option. Does that seem fine? I wasn't able to find a spot where $GLOBALS['wp_tests_options']['active_plugins'] was actually used to load the plugins and update the option (maybe I missed it though).
Thanks! Looking forward to writing some tests. :)
=> Update plugin loading for phpunit

class.two-factor-core.php
Dummy input so $_POST value is passed when no providers are enabled.
Fixes #20
Alternate resolution to #21
=> Add a dummy input.

class.two-factor-core.php, providers/class.two-factor-backup-codes.php
Adds the backup-codes provider to the list of potential methods.  Verification codes are single use and stored in the database as an array of hashed string.  Let me know if you have any questions.
=> Adds Backup Codes Provider

class.two-factor-core.php
Introduces a column on the Users admin listing screen which displays each user's 2FA status.
It displays either `Disabled` for users with no 2FA enabled, or it displays their primary 2FA provider name.
=> Introduce a 2FA column on the Users admin listing screen

providers/class.two-factor-backup-codes.php
You can't break a single string or sentence into two parts, translate separately, and concatenate. This will make the string fully translatable.
=> Combine "out of codes" strings into one string for better translatability

class.two-factor-core.php
I think adding "login_footer" action is better.
Otherwise, footer JS enqueued by wp_enqueue_script() will be lost.
=> Add "login_footer" action

.travis.yml
No need to run Travis-CI tests with WordPress 4.0, but tests should be running against `/trunk`
=> Travis CI: Switch from WP 4.0 to /trunk testing

class.two-factor-core.php, tests/phpunit/tests/providers/class.two-factor-fido-u2f.php
I hit a bunch of fatal errors due to the exceptions in the Yubico code--added a wrapper around get_instance and in the test cases.
=> Catch exceptions when instantiating FIDO U2F

class.two-factor-core.php
https://travis-ci.org/georgestephanis/two-factor/jobs/78647176
/tmp/wordpress/src/wp-content/plugins/two-factor/class.two-factor-core.p
hp:67:105: error - Expected next thing to be an escaping function (see
Codex for 'Data Validation'), not ')'
(WordPress.XSS.EscapeOutput.OutputNotEscaped)
/tmp/wordpress/src/wp-content/plugins/two-factor/class.two-factor-core.p
hp:68:17: error - Expected next thing to be an escaping function (see
Codex for 'Data Validation'), not 'PHP_VERSION'
(WordPress.XSS.EscapeOutput.OutputNotEscaped)
=> This shouldn't need to be escaped, as any escaping should be done on the handler.

class.application-passwords.php, class.two-factor-core.php, providers/class.two-factor-fido-u2f-admin.php
This hook is for methods to insert their UI settings to ensure they are grouped with other two-factor methods.
Before: 
After:
Fixes #55
=> Adds hook at the end of the Two Factor methods table outputted on profile.php

class.two-factor-core.php
In d68ee2b47625edad8f883f1f7b8719343a971179 , my PR missed that `do_action` needed an arg to pass the user data over. This makes the world whole again.
=> Add arg for the settings hook.

class.two-factor-core.php, includes/function.login-header.php
In situations where login_header() is inaccessible (because we’re on a
page other than wp-login.php because of a plugin or something) manually
redefine `login_header()` so we can call it there as well.
Also make sure we’re always submitting to the correct page and links go
to the correct page — `wp_login_url()` — if a plugin changes that, they
should also be reordering things to call the actions we use so that it
still works.
Resolves issues with WooCommerce logins from front-end pages. :+1:
Fixes #61
=> Include a fix for alternate login forms.

providers/class.two-factor-totp.php
=> TOTP: Pre-encode spaces to fix iOS issue with URLs containing spaces

two-factor.php
Without requiring network-wide activation, the plugin can be bypassed by logging in via a site that hasn't enabled it.
=> For multisite uses, require network-wide

providers/class.two-factor-fido-u2f.php
Fixes #123 and #118.
See https://developers.yubico.com/U2F/App_ID.html
=> Always use HTTPS and the TLD for the AppID

class.two-factor-core.php, providers/class.two-factor-backup-codes.php, providers/class.two-factor-dummy.php, providers/class.two-factor-email.php, providers/class.two-factor-fido-u2f-admin-list-table.php, providers/class.two-factor-fido-u2f-admin.php, providers/class.two-factor-fido-u2f.php, providers/class.two-factor-totp.php, tests/providers/class.two-factor-totp.php, two-factor.php
Also adds some translator comments and a `load_plugin_textdomain()` call to satisfy GlotPress. That way, the plugin can be properly translated using https://translate.wordpress.org.
Fixes #139.
=> Add missing text domains

providers/class.two-factor-fido-u2f.php
A possible fix for #148.
I'm not sure about the following:
- Should we be using `home_url()` or `site_url()` for the AppID? Keeping the `home_url()` makes sense because it has worked well so far.
- Some sites might include extra path name in `home_url()` which wasn't there before this change. This will break their U2F login.
- How do we write unit tests for this? I would like to check that the output of `get_u2f_app_id()` always includes `https://`, for example.
=> Include URL protocol in the U2F AppID

providers/class.two-factor-fido-u2f-admin-list-table.php, providers/class.two-factor-fido-u2f-admin.php, providers/class.two-factor-fido-u2f.php, providers/css/fido-u2f-admin.css, providers/js/fido-u2f-admin.js, tests/providers/class.two-factor-fido-u2f.php
Fixes #117 and #78 . Ready for code review.
- Removes all PHP based U2F support detection.
- Introduce error handling when registering new keys.
Here is a notification if U2F browser support can't be detected:
Here are the HTTPS related notifications:
=> Remove server-side U2F support detection

includes/Google/u2f-api.js, providers/class.two-factor-fido-u2f-admin.php, providers/class.two-factor-fido-u2f.php, providers/js/fido-u2f-admin.js
Fixes #165.
Unfortunately there is no official way to detect U2F API support in web browsers. However, in reality only Chrome and Firefox can support U2F.
Chrome supports U2F natively via [`chrome.runtime.sendMessage()`](https://github.com/georgestephanis/two-factor/blob/8b03e926aeee703d8368b108040342f48538592b/includes/Google/u2f-api.js#L196-L206) so we can simply check for `chrome.runtime` and assume that it does support U2F.
The [Firefox U2F extension](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/) works by [creating a global `window.u2f` object](https://github.com/prefiks/u2f4moz/blob/ab97706a178a3299a6568bab7dcdd320108c870f/ext/data/content-script.js#L120) that maps to its internal functions. So we check if `window.u2f` exists before adding the wrapper in …
=> Better U2F Support Detection

providers/class.two-factor-email.php
On the Verification Code screen, currently if you
press return after typing/pasting the code,
'Resend Code' is the submit button that is triggered,
rather than 'Log In', which is confusing for users
as nothing appears to happen when they've provided
the correct code, yet they see ever growing incoming
emails (in the case of email verification).  For
most users Log In would be the expected behaviour.
Similarly, when you tab, Resend Code is the first
button rather than login.
Fixed by changing the order of the buttons in the
HTML (this also makes buttons horizontally aligned).
=> Make 'Log In' button default on verification form

class.two-factor-core.php
The warning about U2F can probably be removed entirely, but this at least won't think about triggering it if it's not enabled.
=> U2F: Don't trigger a PHP warning about U2F if it's not in use.

composer.json
By adding the `"type": "wordpress-plugin"` we can install the plugin to the plugins folder with composer. https://getcomposer.org/doc/04-schema.md#type
=> Allow plugin to be installed in wordpress through composer

class.two-factor-core.php
PR adds a filter on `wpmu_users_columns` so the 2fa info shows when looking at the users in the network admin on a multisite install. I think it's even more important to get an easy overview there compared to on a single site so one can see if all super admins have 2fa activated. :)
=> Add 2fa info column to network admins user list table

composer.json
When adding the package as a mirror in packagist.com you get:
>Validation errors for https://github.com/georgestephanis/two-factor: The package name two-factor is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or \_. The complete name should match "[a-z0-9]\([\_.-]?[a-z0-9]+)\*/[a-z0-9]\([\_.-]?[a-z0-9]+)\*".
=> Add vendor to name property in composer.json

composer.json
Running `composer validate`:
```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
description : The property description is required
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
```
I couln't find license information so I skipped the property.
#237 is related, sorry for not proposing this as a whole.
=> Add description property in composer.json

phpcs.xml, providers/class.two-factor-totp.php, tests/providers/class.two-factor-totp.php
=> Add support for deleting TOTP keys

class.two-factor-core.php
When editing a user other then the current user wrong values are fetched. This problem occurs because of wrong value being passed to method "get_available_providers_for_user".
=> ID instead of WP_User was passed to get providers for current user.

class.two-factor-core.php, tests/class.two-factor-core.php
Fixes #256 and #257.
- Hardcodes the two-factor form action URL to `wp-login.php` (similar to [WP core](https://github.com/WordPress/WordPress/blob/da7a80d67fea29c2badfc538bfc01c8a585f0cbe/wp-login.php#L1082)) since all of the two-factor processing relies on [`login_form_{$action}` hooks](https://github.com/georgestephanis/two-factor/blob/99d654404d2bd908c710649bfc04a37274c23b6b/class.two-factor-core.php#L41-L42).
- Lots of WPCS fixes related to this simple change and the surrounding form HTML.
- Tested that this doesn't introduce regression with custom login forms outside `wp-login.php`, such as WooCommerce.
=> Login action URL

readme.md, readme.txt, two-factor.php
- Mark as tested with WordPress 5.0.
- Always post the two-factor login form to `wp-login.php` which runs all the required hooks for processing. Fixes login issues on WP Engine #257 and when a custom login URL is used #256.
=> Release 0.3.0

providers/js/fido-u2f-admin.js, providers/js/fido-u2f-login.js
Fixes #262.
* remove unnecessary console.log
* remove console.error that are output to the user via a normal error message to avoid duplicate error notifications
* change console.log to .error when no error is output to user
=> remove unnecessary console.log

class.two-factor-core.php
After SSO, we successfully see the two factor verification. The problem is that the query string for SSO is like `?action=jetpack-sso&result=success&user_id=<redacted>&sso_nonce=<redacted>`. If we try to redirect back to that page, we get into a loop where SSO tries to login again, even though we're already logged in (and the nonce is no longer valid). We can redirect to /wp-admin/ instead of `REQEUST_URI`.
=> Fix Jetpack SSO Compatibility

includes/Google/u2f-api.js, providers/class.two-factor-fido-u2f-admin.php, providers/class.two-factor-fido-u2f.php, providers/js/fido-u2f-admin.js
=> Fix U2F feature detection in Firefox

class.two-factor-core.php
Allows us to link directly to the Two-Factor Options from, for example, an admin notice.
=> Add HTML ID to Two-Factor Options

providers/class.two-factor-totp.php
This PR adds the `two_factor_totp_title` filter which allows the TOTP code to be filtered by a site owner. 
Example usage:
```
function my_totp_title(){
return 'My Website';
}
add_filter( 'two_factor_totp_title', 'my_totp_title' );
```
Testing:
Add the filter to a feature plugin or your theme's `functions.php` file then re-add the QR code. 
Fixes #291
=> Add two_factor_totp_title filter to allow TOTP title to be changed by site-owner

class.two-factor-core.php
When a user clicks “Login with WordPress.com”, they’re [logged in with Jetpack](https://github.com/Automattic/jetpack/blob/792b26b5539d07cc35fdd93567942f2ad481eef2/modules/sso/class.jetpack-sso-helpers.php#L246-L257), and then [immediately logged out](https://github.com/WordPress/two-factor/blob/1354d5a5f77ee3d9ebad2266920f01920bde7cbe/class.two-factor-core.php#L238) for the 2FA authentication.
The issue is that Jetpack logs in using [`wp_set_auth_cookie`](https://github.com/Automattic/jetpack/blob/e783446cabd8214aaea261fa5176018b32d9476f/modules/sso.php#L769-L771) and sets the [cookie timeout to a year](https://github.com/Automattic/jetpack/blob/792b26b5539d07cc35fdd93567942f2ad481eef2/modules/sso/class.jetpack-sso-helpers.php#L246-L257), but Two-Factor does this all over again, the …
=> Improve Jetpack SSO and Two Factor compatibility

class-two-factor-core.php, readme.txt
We cannot determine when the user has been actually authenticated after the second factor.
We cannot hook into the `wp_login` nor `set_logged_in_cookie` as this plugin is hooking into this action to remove authentication cookie and present the second factor form.
=> Call an action when user is authenticated

class-two-factor-core.php
This PR adds a filter `two_factor_enabled_providers_for_user` to allow developers to filter the the providers that are enabled for a specific user.
An example of where they may be useful is enabling the email provider for a subset of users.
````php
add_filter( 'two_factor_enabled_providers_for_user', function( $providers, $user_id ) {
$user = get_userdata( $user_id );
if ( in_array( 'editor', $user->roles, true ) {
array_push( $providers, 'Two_Factor_Email' );
}
return array_unique( $providers );
}, 10, 2 );
````
As of right now, the only way to do this that I could find is to filter the user meta, which is fine, but less elegant.
Note: I kept the second parameter of the hook signature as `$user_id : int` as opposed to `$user : WP_User` for uniformity with a few other similar filters.
=> Filter the enabled providers for a user

providers/class.two-factor-email.php
Adds 2 filters, `two_factor_token_email_subject` and `two_factor_token_email_message`, to allow developers to filter the subject line and message of the email that gets sent to users with their access token.
=> Add filter to customize email token mail subject and message

class-two-factor-core.php
The dummy method is confusing for the majority of users and shouldn't be available unless in debug mode.
=> Show the Dummy Method only during debugging

class-two-factor-core.php, providers/class.two-factor-totp.php, tests/providers/class.two-factor-totp.php
Fixes #341.
- Introduce user action API for the plugin that takes care of generating action URLs and validating the inputs via nonces.
- Use the user action API to generate the reset link and delete the secret if the link action validation passes.
- Show OTP registration notices for the correct user -- the current or the one being edited instead of just the current one.
=> Fix the OTP secret delete button

providers/class.two-factor-email.php, tests/providers/class.two-factor-email.php
Fixes #220.
- Keep track of the timestamp when the token was generated.
- Allow the token TTL to be customized via a filter.
=> Add email token expiry

readme.md, readme.txt, two-factor.php
Includes #352 and #351.
- Security fix: escape the U2F key value when doing the key lookup in database during login.
- New feature: invalidate email tokens 15 minutes after they were generated. Use the `two_factor_token_ttl` filter to override this time-to-live interval.
=> Release 0.6.0

.coveralls.yml, docker-compose.yml, package.json, phpunit.xml, tests/docker/wp-dev-lib/Dockerfile, tests/docker/wp-dev-lib/entrypoint.sh, tests/docker/wp-dev-lib/wp-tests-config.php, tests/logs/.gitignore
Introduce a Docker based dev setup for running the PHP unit tests:
- `npm run docker-test` to run the unit tests.
- `npm run docker-lint` to run everything _but_ the unit tests.
- `npm run docker-cli` to support any command.
=> Basic local test support

providers/class-two-factor-totp.php
=> use long array syntax in apply_filters_deprecated() call

providers/class-two-factor-fido-u2f.php
=> Register scripts during *_enqueue_scripts hook instead

providers/class-two-factor-totp.php
Hey,
Thanks for the awesome work with this plugin.
I'm using 1Password to autofill totp-codes, and by setting `d.value = '';` the inserted code gets deleted and I'm not having a good time. This should fix that.
=> fix: login flow for 1Password with totp

two-factor.php
- Fix: improve time-based one-time (TOTP) autofill when using password managers like 1Password, see #373. Props @omelhus.
- Fix: register FIDO U2F related scripts during the suggested action hooks to avoid PHP noticed, see #356 and #368. Props @cojennin.
- Rename and deprecate action and filter names `two-factor-user-options-` and `two-factor-totp-time-step-allowance` that don't following the WP coding standards. Use `two_factor_user_options_` and `two_factor_totp_time_step_allowance` now. See #363. Props @paulschreiber.
- Update codebase to match the WordPress coding standards, see #340. Props @paulschreiber.
- Add tooling to run PHPUnit tests locally during development, see #355. Props @kasparsd.
=> Version 0.7.0

providers/class-two-factor-email.php, tests/providers/class-two-factor-email.php
=> Ensure there are no blank spaces or line breaks around the token

providers/class-two-factor-backup-codes.php
Two-Factor Backup Codes generated like below:
E.g.
1. 26056637
2. 34800832
3. 68473048
4. 28263149
5. 68946117
6. 73912621
7. 70914813
8. 59360534
9. 82345347
10. 59028553
When using all of them then the notice appears. But due to the missing `echo`, it was not displayed.
Now, This displayed as below:
=> Fix: Backup code generate notice not visible.

providers/class-two-factor-email.php
Added wp_specialchars_decode( ) to escape the HTML entity on the Email Subject line #412
=> Update class-two-factor-email.php to escape the HTML entity

class-two-factor-core.php, composer.json, composer.lock, package-lock.json, package.json, phpunit.xml.dist, tests/class-two-factor-core.php
Hash the second factor login screen nonce in storage to avoid leaking it via DB access but pass in unhashed to the second factor input form.
=> Hash the login nonce for storage to avoid leaking it via DB access

readme.txt, two-factor.php
Minor release.
Diff: https://github.com/WordPress/two-factor/compare/0.7.1...13c30418aa54640f739f59b23ed23897b76b4caf
- Security improvement: Store the second factor authentication step nonce hashed to prevent leaking it via database read access [#453](https://github.com/WordPress/two-factor/pull/453). Props to [@calvinalkan](https://github.com/calvinalkan) for reporting the issue.
- Fix: Add `wp_specialchars_decode()` to escape the HTML entity on the Email Subject line ([#412](https://github.com/WordPress/two-factor/issues/412)), props [@nbwpuk](https://github.com/nbwpuk).
- Fix: Use `hash_equals()` when comparing the email token ([#425](https://github.com/WordPress/two-factor/issues/425)), props [@Mati02K](https://github.com/Mati02K).
- Tooling: Introduce `@wordpress/env` for …
=> Release 0.7.2

class-two-factor-compat.php, class-two-factor-core.php, providers/class-two-factor-backup-codes.php
PHP 8.1 [deprecated](https://www.php.net/manual/en/filter.filters.sanitize.php) `FILTER_SANITIZE_STRING`. This PR replaces it with other alternatives.
Ref: Automattic/vip-go-mu-plugins#2667
=> PHP 8.1 compatibility: replace FILTER_SANITIZE_STRING

providers/class-two-factor-totp.php
Hi! This is a little improvement over #373 that included the autocomplete attribute. I've set it attribute to 'one-time-code' so browsers and password managers can autocomplete the code if necessary/possible. I've tested it on the latest versions of 1Password and Safari, Chrome, Firefox & Edge and it autocompletes the TOTP code (previously it only worked on Safari)
Great job with the plugin by the way, thanks!
=> Improve TOTP autocomplete behaviour

.github/workflows/test.yml, class-two-factor-core.php, composer.json, package-lock.json, package.json, user-edit.css
- Add a Composer script to lint for PHP 8.2 support.
- Add the check to CI, too.
- Fix the CSS linter issues introduced by #387.
=> Add PHP8 linter and fix linter issues

.github/workflows/deploy.yml
The automatic deployments introduced in #438 are failing at the last commit step for unknown reason. Disable the attempts until this is fixed.
=> Disable the deployment for now

providers/class-two-factor-totp.php, readme.md, tests/providers/class-two-factor-totp.php
This adds some tests to fill small gaps in coverage, and marks some functions as ignored because they're not testable in a unit test, or aren't worth testing. This increases the coverage of `class-two-factor-totp.php` to `92%`, making it obvious that it is well-tested.
To aid in writing tests, this also adds `phpunit-watcher`, similar to Gutenberg, WordCamp.org, and some other WordPress repos.
See #468
=> Increase TOTP coverage

.github/workflows/test.yml, composer.json, composer.lock, package.json, phpunit-watcher.yml.dist, tests/class-two-factor-core.php, tests/providers/class-two-factor-backup-codes.php, tests/providers/class-two-factor-dummy.php, tests/providers/class-two-factor-email.php, tests/providers/class-two-factor-fido-u2f.php, tests/providers/class-two-factor-totp.php
PHPUnit was updated to the latest version (`9.5`), and function signatures/assertions were updated to match. I also used WP's currently recommended setup/teardown methods and fixtures.
This also installs `phpunit-watcher`, since it makes developing tests much easier. It's used in Gutenberg, WordCamp.org, and several other WP repos.
This was branched off from #469. I belive all of the comments raised there have been addressed:
* Removing the redirect to `/dev/tty` seems to work fine in this environment, but there's more information in https://github.com/spatie/phpunit-watcher/pull/112 if we ever run into it. 
* Watching the root files is working. It seems a little bit slower, but not by a significant amount.
* The `--timeout=0` flag didn't work for me, Composer would still time out after 5 …
=> Update PHPUnit, Install phpunit-watcher

phpunit.xml.dist
I missed this in #472, and this was being shown when running tests:
> Warning:       Your XML configuration validates against a deprecated schema.
> Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
I haven't tested Coveralls since it doesn't seem to be configured (#364, #467), but I verified that the log file is still being generated.
=> Tests: Migrate config to 9.5 format

phpunit-watcher.yml.dist
These should be implicitly ignored because of the `ignoreDotFiles`, `ignoreVCS`, and `ignoreVCSIgnored` settings, but some of them weren't for some reason. That was causing a noticable delay between when a file was saved and when the tests relaunched.
Previously #472
=> Tests: Explicitly ignore directories for performance

class-two-factor-core.php
=> Pass a WP_Error object to the `wp_login_failed` filter.

.github/SECURITY.md, readme.md, readme.txt
=> Add Security Policy

class-two-factor-core.php, tests/class-two-factor-core.php
I noticed a few comments on a closed PR and didn't want them to fall through the cracks:
* [Shorten expiration to ~10 minutes](https://github.com/WordPress/two-factor/pull/453/files#r965622814)
* [Include user ID and expiration in HMAC](https://github.com/WordPress/two-factor/pull/453#issuecomment-1244171674) - cc @calvinalkan 
* ~~It also looks like a valid nonce can be reused many times. IMO it should be deleted once it's been successfully used once. The unit test [says that it checks for this](https://github.com/WordPress/two-factor/blob/be268ba1644d8f5b35761fce790c3b1de1ce86a2/tests/class-two-factor-core.php#L422), but actually checks that an invalid nonce deletes a valid one.~~
I'd appreciate some extra eyes on this one to make sure everything with the HMAC is correct.
=> Harden login nonces

providers/class-two-factor-totp.php
This allows for the renderer to enqueue the TOTP generation on the front-end - Such as within the bbPress settings panel.
Without this, the JS is never loaded and you just see a spinner.
See 70ba42e3bac72597a5b98785b6f11273f2830cb4 & #487
=> Register the TOTP QR generation script on the front-end.

providers/class-two-factor-backup-codes.php, tests/providers/class-two-factor-backup-codes-ajax.php
Fixes #460
- `encodeURI()` doesn't encode enough characters for non-english languages.
- `encodeURIComponent()` doesn't encode enough characters for usage within `data:` uri's
- `i18n.title` should not be HTML escaped if it's not going to be used within a HTML context. This results in the translation string having HTML entities. An alternative would be to decode HTML entities client-side in JS and then use it that value, but encoding it in the first place here provides no security benefits.
=> Fix Backup code download with quotes in translations

class-two-factor-core.php
Based on the feedback in #406 and limited interest on changing how the login flow works in #490, this PR is a minimal patch which prevents sending the authentication cookies upon hitting the 2FA interstitial page.
As there's limited changes in this PR, this should be easier for others to review and approve.
=> Block sending authentication cookies upon 2FA login

providers/class-two-factor-totp.php, tests/providers/class-two-factor-totp.php
Per the [TOTP spec, section 5.2](https://www.rfc-editor.org/rfc/rfc6238#section-5.2):
>    Note that a prover may send the same OTP inside a given time-step
window multiple times to a verifier.  The verifier MUST NOT accept
the second attempt of the OTP after the successful validation has
been issued for the first OTP, which ensures one-time only use of an
OTP.
Once a TOTP token is entered, it should not be able to be re-used, it's one-time.
This is a hardening ticket, making the TOTP provider comply with the spec.
For example:
- have two unique browser sessions open
- generate a TOTP code, CODE1
- Login with user/password/CODE1 on window 1
- Login with user/password/CODE1 on window 2
Per spec, both windows logging in successfully shouldn't be allowed, window 2 should fail the TOTP code …
=> TOTP: Enforce single-use of TOTP one-time passwords.

composer.json, composer.lock
After #522 and #523 I've realised that the composer file included with this repo specifies WordPress 6.0.* only, it didn't have the fixes included in WordPress 6.1 and unit tests have been running against an outdated version of WordPress.
This PR simply updates composer dependencies, and switches from `^6.0` to `~6.0` for WordPress, causing it to install all `6.x.y` releases.
=> Tests: Use WordPress 6.1.1

providers/class-two-factor-provider.php, tests/providers/class-two-factor-provider.php
This was split out of #518 as it's technically unrelated, and is failing for some reason in GitHub actions, but passing locally.
I can't really determine by looking at the code why it's failing though.
=> Add unit tests for Two_Factor_Provider::get_code().

composer.json, phpunit.xml.dist, readme.md
This makes it convenient to check coverage locally, instead of having to go to Coveralls.
This does part of the documentation for #467 , but only the local part. Docs will still need to be added for Coveralls when #364 is done.
=> Tests: Generate an HTML coverage report when running tests locally.

class-two-factor-core.php, tests/bootstrap.php, tests/class-two-factor-core.php
Fixes #477 
Builds on top of #510
After a reasonable number of 2nd-factor attempts, it's safe to assume that the password been compromised and an attacker is trying to brute force the 2nd factor.
`get_user_time_delay()` mitigates brute force attempts, but many 2nd factors -- like TOTP and backup codes -- are very weak on their own, so it's not safe to give attackers unlimited attempts.
Since we know that the password is compromised, we have the responsibility to reset it and inform the user. That will guarantee that attackers can't brute force it (unless they compromise the new password).
=> Core: Reset compromised passwords after 2FA failures

providers/class-two-factor-totp.php
In https://github.com/WordPress/wporg-two-factor/issues/69 it's been realised that the TOTP plugin has a `two_factor_totp_title` filter for the label, but doesn't have one for the `issuer`.
The label is supposed to be in the format of `Issuer: $user` but others may incorrectly only change the prefix of the label without also changing the issuer details.
This PR does two things:
- Documents the existing filters
- Adds a `two_factor_totp_issuer` filter to change the Site name that's then used as part of the label.
=> Document the TOTP Filters, add Issuer filter

class-two-factor-core.php
The new reset-password code added in #482 / #477 fails to take into consideration that the user may have logged in with an email.
This PR does two things:
- Defensive checks, which is especially relevant if a non-username/email login handler is in play
- Fetches a user by email if required
The code here was copied from [here](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-login.php#L1212-L1227) with the addition of replacing `strpos` with `str_contains` for readability.
The code currently triggers a PHP notice such as this during login with a bad password, if email is used:
```
E_NOTICE: Trying to get property 'ID' of non-object in wp-content/plugins/two-factor/class-two-factor-core.php:665
```
=> Support login-by-email in maybe_show_reset_password_notice().

class-two-factor-core.php, tests/class-two-factor-core.php
Currently there's two different routes into the 2FA credentials window, `action=validate_2fa` and `action=backup_2fa`, these are exactly the same, except that the former uses POST and the latter uses GET.
This is partially caused by the usage of `filter_input()` which has other problems for us, such as being unable to be unit tested.
This PR simplifies it by combining `action=validate_2fa` and `action=backup_2fa` and simplifying the resulting code.
This is part of an initial work towards #484.
=> Switch to using `$_REQUEST` directly instead of `filter_input()` and remove `backup_2fa` 

class-two-factor-core.php, tests/class-two-factor-core.php
Currently the various API-level functions accept two main inputs: `ID` or `WP_User`, and assumes that if not provided the function should operate on the current user.
Accepts `WP_User`:
- `Two_Factor_Core::get_enabled_providers_for_user()`
- `Two_Factor_Core::get_available_providers_for_user()`
Accepts `ID`:
- `Two_Factor_Core::get_primary_provider_for_user()`
- `Two_Factor_Core::is_user_using_two_factor()`
When a WP_User is passed in place of an ID, or an ID in place of a WP_User, the functions operate on the current user, which could lead to unexpected responses.
This PR standardises the above 4 functions to:
- Accept `int|WP_User`
- Only default to the current user when no parameters are passed / `null` is passed (The default value for the function param)
- Uses the same user …
=> Standardise on `int|WP_User` input to the "for user" functions

SECURITY.md, readme.txt
This adds an FAQ entry for where to file security bugs.
Per request from the WordPress security team.
The copy used is similar to the one that is already present here in the Gutenberg `SECURITY.md` file, which was used as a reference.
=> Add information about where to submit security bugs

class-two-factor-core.php, providers/class-two-factor-backup-codes.php, providers/class-two-factor-dummy.php, providers/class-two-factor-email.php, providers/class-two-factor-fido-u2f.php, providers/class-two-factor-provider.php, providers/class-two-factor-totp.php, tests/class-secure-dummy.php, tests/providers/class-two-factor-dummy-secure.php, tests/providers/class-two-factor-provider.php
This PR allows for the classname of a provider to differ from it's "key" that's used within the application.
This was spurred by an attempt to simply extend a core provider with a custom one to override certain functions (instead of #545 ).
This has resulted in several changes:
- Filter addition
- Removing variables like 'class' and replacing them with 'provider_key'
- Addition of a `Two_Factor_Provider::get_key()` which returns the providers 'key', which defaults to the class name as present.
- removing `get_instance()` from each individual provider and moving it to the abstract `Two_Factor_Provider`, each provider had a slightly different one, and the usage of `__CLASS__` meant children of the provider had to override the `get_instance()` method as well.
This allows for users of the …
=> Add a filter to filter the classname used for a provider

readme.txt
Update the "Tested up to" tag in the readme.txt file.
If the tag does not match the current WordPress version, the "This plugin has not been tested with your current version of WordPress." warning is displayed when viewing the plugin details in wp-admin. Also, when searching for the plugin in wp-admin of a site, the notice "Untested with your version of WordPress" is shown.
The "Tested up to" tag has been set to 6.2 in the readme.txt file.
Validated:
- Email
- Time Based One-Time Password (TOTP)
- Backup Verification Codes (Single Use)
- Dummy Method
Fixes #540
=> Bump tested up to version

class-two-factor-core.php, tests/class-two-factor-core.php
This PR is part of some larger work for #484.
This PR causes the two-factor timestamp and provider to be stored in the user session, which can be later used to validate that the user session is two-factor authenticated.
|Before|After|
|---|---|
| <img width="791" alt="Screenshot 2023-02-20 at 2 45 59 pm" src="https://user-images.githubusercontent.com/767313/220011599-86bc00df-6ecb-4534-8a7b-6c9142720522.png"> | <img width="782" alt="Screenshot 2023-02-20 at 2 45 46 pm" src="https://user-images.githubusercontent.com/767313/220011622-bcbcdd63-34e8-4629-ab55-5ebbc19983f2.png"> |
Code Notes:
- The 'attach_session_information' hook is poorly designed for this case, requiring the usage of an anonymous function so as to retrieve the details from the current-scope of the class.
- It's possible …
=> Store the two-factor details in the user session at login time

providers/class-two-factor-backup-codes.php, providers/class-two-factor-totp.php
Fixing bug where WP VIP Super Admins and WooCommerce shop_manager cannot setup Time Based One-Time Password as their first Two Factor option. Please have a look at #559 for more detailed information.
Fixes #559
Fixes #557
I am setting the controller parameter configuration to have user_id as an integer instead of a number because strict comparison requires matching types.
1. Setup a multisite
2. Create a new user that is a super_admin
3. Log in as the new super_admin
4. Go to `wp-admin` > `Edit Profile`
5. Submit an authentication code
Fixing bug where WP VIP Super Admins and WooCommerce shop_manager cannot setup Time Based One-Time Password as their first Two Factor option
Original PR: [https://github.com/Automattic/vip-go-mu-plugins/pull/4410](https://github.com/Automattic/vip-go-mu-plug …
=> Fixing bug where Super Admins cannot setup Time Based One-Time Password as first Two Factor option on WP VIP

providers/class-two-factor-backup-codes.php, providers/class-two-factor-totp.php
Enqueues jQuery and wp-api-request as required by the JS UI handlers.
Fixes #558
These are dependencies of the JS.
See #558
=> Enqueue jQuery and wp.apiRequest for use within callbacks.

class-two-factor-core.php, tests/class-two-factor-core.php
See #565, #566
This centralises the provider selection into it's own method for clarity around it's logic, resolving a fatal error in the process, but replacing it with a dead-end `Cheating huh?` style error. This error condition should not be possible to be hit under normal circumstances.
More importantly, this adds Session metadata helpers (That should probably be provided by core) for retrieving/updating the current user session.
Through that, the 2fa-session flag is cleared upon the providers being disabled.
In comparison to #566 this resolves the underlying fatal in a way that can't be reintroduced, fixes some merge bugs (ie. `get_class( $provider )` is replaced by `$provider->get_key()`), and reduces code duplication.
The unit test from #566 is included.
See #565 #566
N/A - Bugfix …
=> ReAuth: resolve fatal, code cleanup

class-two-factor-core.php, tests/class-two-factor-core.php
Copies two-factor session information from the current session to newly created sessions.
Fixes #573
WordPress creates a new session when the user changes their password, for no particular reason.
See https://core.trac.wordpress.org/ticket/58427
See https://github.com/WordPress/wporg-two-factor/issues/191
See screen recording. The debug shown is from this change:
```diff
diff --git a/class-two-factor-core.php b/class-two-factor-core.php
index 53fa43b..ce5b197 100644
--- a/class-two-factor-core.php
+++ b/class-two-factor-core.php
@@ -1718,6 +1718,11 @@ class Two_Factor_Core {
$show_2fa_options ? '' : 'disabled="disabled"',
);
+       echo '<pre>'; var_dump( [
+               'token' => wp_get_session_token(),
+               'session' => Two_Factor_Core::get_current_user_session(),
+ …
```
=> Sync two-factor session meta to newly created sessions

class-two-factor-core.php, tests/class-two-factor-core.php
Two-Factor includes a nonce during the validate_2fa callback, and while the fields are present in the POST request for the revalidate endpoint, it's not used.
Props @xknown for the report.
A nonce should be present on all POST requests that perform actions, to prevent potential CSRF attacks.
Due to the revalidation occurring with an authenticated session, `wp_create_nonce()` is used to validate the request. The Two-Factor login_nonce functionality is not used, to ensure that the revalidate nonce can't be used to login a new session.
The nonce is ignored during GET requests for the revalidate endpoint.
- The initial load of the revalidate screen can be sans-nonce, this is not a concern IMHO. 
- The change-provider link DOES include a nonce, but it is not validated. This is due to …
=> Require a nonce be present for revalidate POST requests.

class-two-factor-core.php, tests/class-two-factor-core.php
Upon a new 2FA provider being set, existing sessions for the user are destroyed.
Fixes #577
It's considered best-practice to terminate existing sessions when "enhancing" an authenticated session.
For the current user, the active session is kept, other sessions are destroyed upon 2FA being activated.
For other users, all their sessions are terminated.
See #577 
Security - When 2FA is activated for a user, destroy any existing sessions.
=> Destroy existing sessions when activating 2FA.

class-two-factor-core.php, tests/class-two-factor-core.php
Adds a `Two_Factor_Core::disable_provider_for_user()`  method.
This provides parity with the `Two_Factor_Core::enable_provider_for_user()` method. It's not currently used by Two Factor itself, but it allows plugins to disable an individual provider directly, rather than having to know the internals and update meta keys, etc.
One example use case for that is https://github.com/WordPress/wporg-two-factor/pull/223#pullrequestreview-1570860929, where a custom front-end UI was developed in React, using REST API endpoints.
Fixes #585 
1. Enable a provider via `wp-admin/profile.php` and save
2. Add the following code in an mu-plugin. Replace the name of the provider with one you enabled.
add_action( 'init', function() {
Two_Factor_Core::disable_provider_for_user( get_current_user_id(), …
=> Add method to disable an individual provider

class-two-factor-core.php, providers/class-two-factor-fido-u2f-admin.php, tests/bootstrap.php
Using "require_once" everywhere, replacing a few inconsistent "require" and "include_once" usages
I'm being a silly and manually including a file in another plugin
By using require_once, we'll all get to bypass some PHP warnings that don't appear to be intended behavior as-is
Install the latest Github master branch of the WP User Profiles plugin, navigate to your Admin Area Profile page, and visit the "Account" tab. Once there, you'll see a glorious warning because we're already (manually) including one of the files in this plugin
Prefer "require_once" in a few spots.
This change prevents unintended PHP warnings when silly JJJ people are doing silly JJJ things.
Fixes #594.
=> issue/594 - Prefer "require_once" in a few spots.

two-factor.php
Create a release with the following changes https://github.com/WordPress/two-factor/compare/0.8.2...release/next 
This is a large release with lots of changes and improvements to how the two-factor data is processed.
- Users are now asked to re-authenticate with their two-factor before making changes to their two-factor settings #529. This builds on #528 which associates each login session with the two-factor login meta data for improved handling of that session.
Generated via `git log 0.8.2...release/next --oneline --reverse --first-parent`:
fd9a058 Merge pull request #551 from pkevan/patch-2
c490519 Allow filtering the PHP classname used for a provider (#546)
ed75664 Bump tested up to version (#552)
836ef62 Store the two-factor details in the user session at login time (#528)
f027b04 …
=> Release 0.9.0

.github/workflows/deploy.yml, .github/workflows/test.yml, .gitignore, composer.json, composer.lock
- Enable PHP compatibility linter that ensures all plugin code is compatible with PHP 5.6 or later. That's until we bump the required version of PHP.
- Bump development specific dependencies to the latest versions.
This now would catch issues like #604:
=> Ensure PHP 5.6+ support during CI to avoid breaking changes

class-two-factor-core.php, readme.txt, two-factor.php
Removes the manual `load_plugin_textdomain()` call to rely on WordPress to load translations at the right time.
Bumps the requirement to WordPress 4.6 accordingly.
Also, defines the `Requires *` headers in the main plugin file so that WordPress can actually read them and prevent you from installing the plugin if requirements are not met.
The headers mustn't really be set in the readme.
The plugin was loading translations too early on `plugins_loaded`. Plugins should wait until `init` to ensure the current user has been set up, so that the current user's locale can be respected.
That said, why manually load translations when WordPress can do it for you :-)
Switch to a different language and see that the translations are still loaded as expected.
> Fixed - Ensured translations are only …
=> Rely on just-in-time translation loading

readme.txt, two-factor.php
This PR shortens the short description to be within the WP.org 150 character requirement.
Prior short description: Enable Two-Factor Authentication using time-based one-time passwords (OTP, Google Authenticator), Universal 2nd Factor (FIDO U2F, YubiKey), email, and backup verification codes.
New short description: Enable Two-Factor Authentication using time-based one-time passwords, Universal 2nd Factor (FIDO U2F, YubiKey), email, and backup verification codes.
WP.org truncates the Short Description if its longer than 150 characters, we don't want that truncated, so this PR shortens it to under 150 characters.
Changes the short description in readme.txt as well as the roughly matching description headed in two-factor.php.
Use an [Online Character Count …
=> Update short description

class-two-factor-core.php
This adds an action for when a user revalidates their session.
This is similar to the existing `two_factor_user_authenticated` action for when the user authenticated via 2FA in the first place.
I'm needing to have a cookie set for when the revalidation logic is triggered, and neither Two-Factor nor WordPress (in it's session handler) have a way to detect that the current sessions 2FA has been revalidated / modified.
Added - A New hook was added that fires when a user revalidates their 2FA session.
=> Fire an action when a user revalites their 2FA session.

composer.json, two-factor.php
Fixes #461
Increases the PHP & WP minimum requirements.
Because we can. But also because the automated testing isn't going to cover these old versions, and nor should we.
Changed - This plugin now requires PHP 7.2 and WordPress 6.3 or later.
=> Bump minimum WP to 6.3, minimum PHP to 7.2.

class-two-factor-core.php, providers/class-two-factor-totp.php
Fixes #536 this improves the accessibility for the options page by:
- Setting the heading to a H2 as appropriate for the page
- Adds a title to the QR code and marks it as an image, based on https://stackoverflow.com/a/4756461
The QR library we use does not provide the needed ability to set the title/role, which is why I've used JS to set these.
I'm not sure of the best text to use as a `title` for the QR code, but I think `Authenticator App QR Code` is reasonably descriptive yet short enough.
This makes the page more accessible to screen readers
Fixed - Improved accessibility of the options screen.
=> Accessibility for options page

tests/providers/class-two-factor-totp.php
In #619 the return value of a method was changed to `void` which caused an old test to fail.
Consider that the method was used for pure output, there is no value in testing that method separately. Removing it.
See the automated tests in CI passing.
=> Fix failing unit test

.distignore, .github/workflows/test.yml, .gitignore, class-two-factor-compat.php, class-two-factor-core.php, composer.json, composer.lock, package.json, phpstan.dist.neon
Introduces [phpstan](https://phpstan.org) with WordPress core stubs through [szepeviktor/phpstan-wordpress](https://github.com/szepeviktor/phpstan-wordpress).
Fixes #618.
Static analysis helps us uncover potential bugs and edge cases. Introducing the tooling didn't require a lot adjustments thanks to work already done in #619.
Add the tooling as Composer development dependency and introduce additional lint scripts in `composer.json` and `package.json`.
1. Install composer dependencies via `composer install` after checking out this branch.
2. Run `composer lint-phpstan` and confirm that `[OK] No errors` is returned.
Development: Introduce PHPstan tooling for development.
=> Add basic PHPStan linter

class-two-factor-core.php
Fixes #485.
Encourage users to configure at least two two-factor methods to prevent them from being locked out of account in case of loosing access to the primary method.
Showing a notice before any of the methods are configured _and_ when only one method is configured.
1. Setup a plugin and go to your profile to setup the methods.
2. Select only email, save the settings and confirm that a message is shown suggesting to setup another method.
No methods configured:
Only one method configured:
Multiple notices:
Added a notice to the user profile suggesting to configure at least two two-factor methods for ensuring access.
=> Encourage setting up a second recovery method 

providers/class-two-factor-totp.php
This PR updates the UX for when TOTP is checked it focuses in the code input, fixes https://github.com/WordPress/two-factor/issues/159
For better UX as requested in https://github.com/WordPress/two-factor/issues/159 
Adds an event listener to check when the checkbox is enabled to focus into the code.
Start the env after checking out into the branch go to http://localhost:8888/wp-admin/profile.php, scroll down two factor options, confirm it focuses into the input.
https://share.cleanshot.com/qWNlb6gQTp90hDS8Fq0Q
> Changed - UX update, focus into code input when TOTP is enabled
=> Focus in code input when totp is checked

class-two-factor-core.php, tests/class-two-factor-core.php
See https://github.com/WordPress/two-factor/pull/637#discussion_r1831364092
In #637 we introduced a dedicated helper to retrieve all possible two-factor providers (even if disabled) so that we could purge all their added user meta and options during uninstall.
Accidentally it added another instance of the `two_factor_providers` filter which was already defined in `get_providers()`.
- Introduce a method for getting the default built-in providers. This is used as the starting point for enabled providers and when collecting all providers to clean during plugin uninstall.
- Pass that default list of providers to the `two_factor_providers` filter when getting "enabled" providers from `get_providers()`.
- Refactor `get_providers_classes()` to accept a list of provider names and their class …
=> Remove duplicate `two_factor_providers` filter calls to allow disabling core providers

providers/class-two-factor-backup-codes.php, providers/class-two-factor-email.php, providers/class-two-factor-totp.php
This PR disables autocompletion for authcode input fields. 
Since authcode are always unique, autocompletion is not useful here.
Added - Disabled autocompletion for authcode input fields.
Fixed - Corrected input type.
=> Add autocomplete "one-time-code" attribute

providers/class-two-factor-backup-codes.php, providers/class-two-factor-email.php, readme.txt, tests/providers/class-two-factor-backup-codes.php, tests/providers/class-two-factor-email.php
Fixes #374.
Replaces #419.
Implements two new filters:
- `two_factor_email_token_ttl` filter overrides the default 8 character count for email tokens. This has been renamed from `two_factor_token_ttl` which is now marked as deprecated.
- `two_factor_backup_code_length` filter overrides the default 8 character count for backup codes. Providers the `WP_User` of the associated user as the second argument.
Users might want to increase this.
- Introduce the filters and rename existing ones for consistency. Add tests to confirm both old and new filters are working.
- Updated the input field placeholders to match the expected character length. Note that this might give away the expected character length for a brute force attacker but we're rate limiting these attempts so that is not an issue. …
=> Add filters for email token and backup code length

class-two-factor-core.php, providers/class-two-factor-totp.php, tests/class-two-factor-core.php
Users expect a method to be enabled if they chose to configure it.
Fixes #556.
Setup workflow:
1. Configure the TOTP method by submitting the generated code.
2. Confirm the TOTP method is now enabled in the table.
Reset workflow: 
1. Click on RESET TOTP method button.
2. Confirm the TOTP method is now disabled in the table.
https://github.com/user-attachments/assets/bd3a9143-86b5-4fa9-b31d-4e27f395f391
=> Enable TOTP method when method is configured

readme.txt, two-factor.php
Get a release out that fixes #651 mostly.
* Remove duplicate `two_factor_providers` filter calls to allow disabling core providers by @kasparsd in https://github.com/WordPress/two-factor/pull/651
* Encourage setting up a second recovery method  by @kasparsd in https://github.com/WordPress/two-factor/pull/642
* Focus in code input when totp is checked by @thrijith in https://github.com/WordPress/two-factor/pull/645
* Add autocomplete "one-time-code" attribute by @stefanmomm in https://github.com/WordPress/two-factor/pull/657
* Add filters for email token and backup code length by @kasparsd in https://github.com/WordPress/two-factor/pull/653
* Enable TOTP method when method is configured by @kasparsd in https://github.com/WordPress/two-factor/pull/643
* @stefanmomm made their first …
=> Release 0.11.0

includes/Yubico/U2F.php
PHP 8.4 requires `null` values to be explicitly declared: https://www.php.net/manual/en/migration84.deprecated.php
This PR does that for the U2F.php class fixing the warning:
> u2flib_server\Error::__construct(): Implicitly marking parameter $previous as nullable is deprecated, the explicit nullable type must be used instead
To avoid noise in the PHP logs and it is likely this may be a fatal in a future version of PHP.
This adds a `?` to the class to allow it to be explicitly null.
Install PHP 8.4, make the change in the PR and watch the error go away.
Fixed - PHP 8.4: Implicitly marking parameter $previous as nullable is deprecated (#663)
=> Fix PHP 8.4 Implicitly marking parameter $previous as nullable is deprecated

two-factor.php
* Fix PHP 8.4 Implicitly marking parameter $previous as nullable is deprecated by @BrookeDot in https://github.com/WordPress/two-factor/pull/664
* Simplify the Two Factor settings in user profile by @kasparsd in https://github.com/WordPress/two-factor/pull/654
**Full Changelog**: https://github.com/WordPress/two-factor/compare/0.11.0...master
=> Release 0.12.0

class-two-factor-core.php, providers/class-two-factor-fido-u2f-admin.php, providers/class-two-factor-provider.php, readme.txt, tests/class-two-factor-core.php
1. Add a filter to allow limiting the available providers per user.
2. Skip rendering the provider table if no providers are available for a user.
Fixes #647, #662.
1. Introduce a new method `get_supported_providers_for_user( $user )` which wraps the output of `get_providers()` in a filter `two_factor_providers_for_user`.
2. Use the new helper whenever we're looking for two-factor methods that should be available to a user.
Note that we already similar methods:
- `get_enabled_providers_for_user( $user = null )` for the provider _keys_ that are enabled in the user profile **but might not be configured, yet**.
- `get_available_providers_for_user( $user = null )` for the provider _keys_ that **are both enabled and configured**.
so I chose the name `supported` to designate if a provider is …
=> Add a filter to limit two-factor providers available to each user

readme.txt, two-factor.php
- Minor version bump 0.13.0 since we're adding features with no breaking changes.
- Mark as tested with the latest version of WordPress core.
* Add a filter to limit two-factor providers available to each user by @kasparsd in https://github.com/WordPress/two-factor/pull/669
* Update automated testing to cover PHP 8.4 and default to PHP 8.3 by @BrookeDot in https://github.com/WordPress/two-factor/pull/665
**Full Changelog**: https://github.com/WordPress/two-factor/compare/0.12.0...master
=> Release 0.13.0

Gruntfile.js, assets/blueprints/blueprint.json, package.json, readme.md
Add support for WP.org playground feature.
Fixes #661.
1. Add `blueprints/blueprint.json` to the `assets` directory which is synced with WP.org SVN `/assets`.
2. Add `npm run blueprint` helper script to generate the blueprint URL for testing.
1. Clone this pull request.
2. Run `npm run blueprint` and visit the generated URL.
Or simply visit: https://playground.wordpress.net/#%7B%22$schema%22:%22https://playground.wordpress.net/blueprint-schema.json%22,%22landingPage%22:%22/wp-admin/profile.php%22,%22preferredVersions%22:%7B%22php%22:%227.4%22,%22wp%22:%22latest%22%7D,%22steps%22:%5B%7B%22step%22:%22login%22%7D,%7B%22step%22:%22installPlugin%22,%22pluginData%22:%7B%22resource%22:%22wordpress.org/plugins%22,%22slug%22:%22two-factor%22%7D,%22options%22:%7B%22activate%22:true%7D%7D%5D%7D
The …
=> Add WP.org plugin demo

.github/workflows/test.yml, readme.txt, two-factor.php
This pull request updates compatibility and documentation for the Two-Factor plugin, ensuring alignment with the latest WordPress and PHP version requirements. The most important changes include updating the minimum required WordPress version, enhancing the plugin's documentation, and modifying the testing matrix in the workflow configuration.
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L82-R82): Updated the WordPress testing matrix to include version `6.7` instead of `6.3`.
* [`two-factor.php`](diffhunk://#diff-d7f63024e0fd3161db0f3a91048d5be3b18c50197b4b6984e5dd6e0ba41bed35L15-R15): Changed the minimum required WordPress version from `6.3` to `6.7`.
* [`readme.txt`](diffhunk://#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e5 …
=> Add/reqs policy & related updates

class-two-factor-core.php
Suggested fix for issue #300
Proposed fix for #300: when a user is authenticated using an application password no 2factor is needed.
Re #300
Depending of if the `application_password_did_authenticate` action has run the plugin now passes `TRUE` (did run) or `FALSE` (did not run) through the `two_factor_user_api_login_enable` filter in the `is_user_api_login_enabled` function.
1. Install the WordPress app on your device
2. Create an application password and login with your WordPress app
If you succeed my PR works, if you can't login my PR does not work.
Fixed #300
Added application passwords support.
=> Fix #300: support for application passwords

readme.txt, two-factor.php
Diff: https://github.com/WordPress/two-factor/compare/0.13.0...master
Features:
* Enable Application Passwords for REST API and XML-RPC authentication (by default) by @joostdekeijzer in https://github.com/WordPress/two-factor/pull/697 and https://github.com/WordPress/two-factor/pull/698. Previously this required `two_factor_user_api_login_enable` filter to be set to `true` which is now the default during application password auth. XML-RPC login is still disabled for regular user passwords.
* Label recommended methods to simplify the configuration by @kasparsd in https://github.com/WordPress/two-factor/pull/676 and https://github.com/WordPress/two-factor/pull/675
Documentation:
* Add WP.org plugin demo by @kasparsd in https://github.com/WordPress/two-factor/pull/667
* Document supported …
=> Release 0.14.0

.github/workflows/deploy.yml, .github/workflows/test.yml
Bump GitHub action runners to known stable versions.
Locks the GitHub Actions runners to `ubuntu-24.04`.
Fixes #702.
=> Use working GitHub Action runners

class-two-factor-core.php, phpcs.xml.dist, providers/class-two-factor-backup-codes.php, providers/class-two-factor-email.php, providers/class-two-factor-fido-u2f-admin.php, providers/class-two-factor-fido-u2f.php, providers/class-two-factor-provider.php, providers/class-two-factor-totp.php, tests/bootstrap.php, tests/class-secure-dummy.php, tests/class-two-factor-core.php, tests/providers/class-two-factor-backup-codes-rest-api.php, tests/providers/class-two-factor-backup-codes.php, tests/providers/class-two-factor-dummy-secure.php, tests/providers/class-two-factor-dummy.php, tests/providers/class-two-factor-email.php, tests/providers/class-two-factor-provider.php, tests/providers/class-two-factor-totp-rest-api.php, tests/providers/class-two-factor-totp.php, tests/two-factor.php
Fixed linting issues.
There were lot of linting issues especially in tests. This PR fixed some of these issues and also excludes security related sniffs from tests.
Fixed - Linting issues in code
=> Fixed linting issues
